apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-rjv5
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0017-tenant/tkrw-pr712-0075-0017-app/devfile-sample-rjv5@sha256:9bc28823a24a39280640844d4c39bb1c31fbcc5d0baf41d8ace29f3a29a305b5
        name: my-nodejs
        resources: {}
status: {}
